// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB058B57WvAeH1rlZ79BNnT8efKdkQek_U',
    appId: '1:152173321595:web:a1382013b00a7784f731de',
    messagingSenderId: '152173321595',
    projectId: 'authentication-2be47',
    authDomain: 'authentication-2be47.firebaseapp.com',
    storageBucket: 'authentication-2be47.appspot.com',
    measurementId: 'G-2VGDV4ZJ10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALG9NPc8lpg25T-0lCL01lMrFQq1ArhWo',
    appId: '1:152173321595:android:c2f8f250206bf14cf731de',
    messagingSenderId: '152173321595',
    projectId: 'authentication-2be47',
    storageBucket: 'authentication-2be47.appspot.com',
  );
}
